import { type TRole } from '@/types/roles';

export const rolesData: TRole[] = [
  {
    id: '1',
    roleName: 'Products',
    name: 'create-product',
    label: 'CREATE',
    checked: false,
  },
  {
    id: '2',
    roleName: 'Products',
    name: 'read-product',
    label: 'READ',
    checked: false,
  },
  {
    id: '3',
    roleName: 'Products',
    name: 'update-product',
    label: 'UPDATE',
    checked: false,
  },
  {
    id: '4',
    roleName: 'Products',
    name: 'delete-product',
    label: 'DELETE',
    checked: false,
  },
  {
    id: '5',
    roleName: 'Employees',
    name: 'create-employee',
    label: 'CREATE',
    checked: false,
  },
  {
    id: '6',
    roleName: 'Employees',
    name: 'read-employee',
    label: 'READ',
    checked: false,
  },
  {
    id: '7',
    roleName: 'Employees',
    name: 'update-employee',
    label: 'UPDATE',
    checked: false,
  },
  {
    id: '8',
    roleName: 'Employees',
    name: 'delete-employee',
    label: 'DELETE',
    checked: false,
  },
  {
    id: '9',
    roleName: 'Customers',
    name: 'create-customer',
    label: 'CREATE',
    checked: false,
  },
  {
    id: '10',
    roleName: 'Customers',
    name: 'read-customer',
    label: 'READ',
    checked: false,
  },
  {
    id: '11',
    roleName: 'Customers',
    name: 'update-customer',
    label: 'UPDATE',
    checked: false,
  },
  {
    id: '12',
    roleName: 'Customers',
    name: 'delete-customer',
    label: 'DELETE',
    checked: false,
  },
  {
    id: '13',
    roleName: 'Roles',
    name: 'create-role',
    label: 'CREATE',
    checked: false,
  },
  {
    id: '14',
    roleName: 'Roles',
    name: 'read-role',
    label: 'READ',
    checked: false,
  },
  {
    id: '15',
    roleName: 'Roles',
    name: 'update-role',
    label: 'UPDATE',
    checked: false,
  },
  {
    id: '16',
    roleName: 'Roles',
    name: 'delete-role',
    label: 'DELETE',
    checked: false,
  },

  {
    id: '17',
    roleName: 'Attributes',
    name: 'create-attribute',
    label: 'CREATE',
    checked: false,
  },
  {
    id: '18',
    roleName: 'Attributes',
    name: 'read-attribute',
    label: 'READ',
    checked: false,
  },
  {
    id: '19',
    roleName: 'Attributes',
    name: 'update-attribute',
    label: 'UPDATE',
    checked: false,
  },
  {
    id: '20',
    roleName: 'Attributes',
    name: 'delete-attribute',
    label: 'DELETE',
    checked: false,
  },

  {
    id: '21',
    roleName: 'Categories',
    name: 'create-category',
    label: 'CREATE',
    checked: false,
  },
  {
    id: '22',
    roleName: 'Categories',
    name: 'read-category',
    label: 'READ',
    checked: false,
  },
  {
    id: '23',
    roleName: 'Categories',
    name: 'update-category',
    label: 'UPDATE',
    checked: false,
  },
  {
    id: '24',
    roleName: 'Categories',
    name: 'delete-category',
    label: 'DELETE',
    checked: false,
  },

  {
    id: '25',
    roleName: 'Orders',
    name: 'create-order',
    label: 'CREATE',
    checked: false,
  },
  {
    id: '26',
    roleName: 'Orders',
    name: 'read-order',
    label: 'READ',
    checked: false,
  },
  {
    id: '27',
    roleName: 'Orders',
    name: 'update-order',
    label: 'UPDATE',
    checked: false,
  },
  {
    id: '28',
    roleName: 'Orders',
    name: 'delete-order',
    label: 'DELETE',
    checked: false,
  },
];
